world:
  weather:
    cloudiness: 95
    fog_density: 7
    wetness: 100
    precipitation_deposits: 85
    fog_distance: 0.75
    fog_falloff: 0.1
    precipitation: 100
    wind_intensity: 90
    sun_altitude_angle: 60
    rayleigh_scattering_scale: 0.02
    scattering_intensity: 1

dataset_config:
  weather: "hard_rain_day"
  weather_abbreviation: "hrd"