world:
  weather:
    cloudiness: 70
    fog_density: 5
    wetness: 80
    precipitation_deposits: 20
    fog_distance: 0.75
    fog_falloff: 0.1
    precipitation: 30
    wind_intensity: 30
    sun_altitude_angle: 60
    rayleigh_scattering_scale: 0.02
    scattering_intensity: 1

dataset_config:
  weather: "soft_rain_day"
  weather_abbreviation: "srd"